### ISSUE TITLE
Files should use defined('MOODLE_INTERNAL') || die(); 

### ISSUE THREAD

**Issue by purnendudash** [moodleus/moodle-tool_lazycron#2]
If a php file should not be loaded on it's own (class files etc) then you should be adding a check to:
defined('MOODLE_INTERNAL') || die();

at the top of the file.

https://github.com/moodleus/moodle-tool_lazycron/blob/1838db0bafa6e795de17dceb51e90cadb7aced6d/classes/plugininfo.php#L26

**Comment by danmarsden** [comment]
Thanks Purnendu, I think that's the "old" way of doing things - since the policy change in [MDLSITE-5967](https://tracker.moodle.org/browse/MDLSITE-5967), when a file only contains a class, and no inline php code then you don't need the defined('MOODLE_INTERNAL') check.

this should be closed off as not an issue.

**Comment by purnendudash** [comment]
@danmarsden Thanks for sharing the same. Will keep that in mind :)

Closing this now.
